server:
  port: '8087'

spring:
  profiles:
    active: local
  application:
    name: bootcoins

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: 'true'
    restart:
      enabled: 'true'

backend:
  service:
    account: 'http://account-service/accounts'